docker-build:
  image: docker:20
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - export CI_VERSION=$(cat server/res/version.txt | awk NF)
    - export TODAY=`date +"%Y-%m-%d"`
    - cat docker-readme.md | sed "s/{{version}}/${CI_VERSION}/g" | sed "s/{{date}}/${TODAY}/g" > docker-readme-modified.md
  script:
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_VERSION --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker run --rm -v $PWD/docker-readme-modified.md:/workspace/README.md:ro -e DOCKERHUB_USERNAME="$CI_REGISTRY_USER" -e DOCKERHUB_PASSWORD="$CI_REGISTRY_PASSWORD" -e DOCKERHUB_REPOSITORY="$CI_REGISTRY_IMAGE" -e README_FILEPATH='/workspace/README.md' peterevans/dockerhub-description:2
