name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set version env
      run: echo "CI_VERSION=$(cat server/res/version.txt | awk NF)" >> $GITHUB_ENV
    - name: Set date env
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Prepare Docker Hub Readme
      run: cat docker-readme.md | sed "s/{{version}}/${CI_VERSION}/g" | sed "s/{{date}}/${TODAY}/g" > docker-readme-modified.md
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build TypeScript commons
      working-directory: ./commons/ts
      run: npm install && npm run build
    - name: Build Admin UI
      working-directory: ./admin-ui
      run: npm install && REACT_APP_PRODUCT_VERSION=$(cat ../server/res/version.txt | awk NF) npm run build
    - name: Build Booking UI
      working-directory: ./booking-ui
      run: npm install && REACT_APP_PRODUCT_VERSION=$(cat ../server/res/version.txt | awk NF) npm run build
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: seatsurfing
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          seatsurfing/backend:${{ env.CI_VERSION }}
          seatsurfing/backend:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: seatsurfing
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
        repository: seatsurfing/backend
        readme-filepath: ./docker-readme-modified.md
