name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: golang:1.23-alpine

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_DB: seatsurfing_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Install Node
      run: apk add --update nodejs npm

    - name: Install server dependencies
      working-directory: ./server
      run: go get -d -v ./...
    - name: Run server in background
      working-directory: ./server
      run: |
        ./run.sh &
        sleep 5

    - name: Build TypeScript commons
      working-directory: ./commons/ts
      run: npm install && npm run build

    - name: Install Admin UI dependencies
      working-directory: ./admin-ui
      run: npm install
    - name: Run Admin UI in background
      working-directory: ./admin-ui
      run: |
        npm run dev &
        sleep 5

    - name: Install dependencies
      working-directory: ./e2e
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./e2e
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./e2e
      run: npx playwright test
