name: Run Tests

on: [pull_request, workflow_dispatch]

jobs:

  container-job:
    runs-on: ubuntu-latest
    container: golang:1.17-alpine

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_DB: seatsurfing_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install server dependencies
      working-directory: ./server
      run: go get -d -v ./...
    - name: Run server tests
      working-directory: ./server
      run: go test -cover -v
      env:
        POSTGRES_URL: postgres://postgres:root@postgres/seatsurfing_test?sslmode=disable
        CGO_ENABLED: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build TypeScript commons
      working-directory: ./commons/ts
      run: npm install && npm run build
    - name: Install Booking UI dependencies
      working-directory: ./booking-ui
      run: npm install
    - name: Run Booking UI linting
      working-directory: ./booking-ui
      run: npm run lint
    - name: Install Admin UI dependencies
      working-directory: ./admin-ui
      run: npm install
    - name: Run Admin UI linting
      working-directory: ./admin-ui
      run: npm run lint